#' Human pancreatic islet data

#'

#' This is the Human pancreatic islet dataset (GSM2230757). The raw data contains 20,125 genes and 1,937

#' cells. Here we use the reference and downsampled datasets generated by Huang et al (2018) which contain

#' 2,284 genes and 1,076 cells (available at https://github.com/mohuangx/SAVER-paper/tree/master/SAVER-data).

#' For details about the approach to generate the reference and downsampled

#' datasets, please refer to Huang et al (2018). This data is an object of class list of length two. count.ref is the

#' reference count matrix and count.samp is the downsampled count matrix.

#'

#' @examples

#' data("baron")

#' @author Ke Jin, \email{kej13@mails.ccnu.edu.cn}

#' @references Baron, Maayan, et al (2016). A single-cell transcriptomic map of the human and mouse pancreas reveals inter-and intra-cell population structure. \emph{Cell systems}, 3(4):346-360.

#' @references Huang, M. et al. (2018). Saver: gene expression recovery for single-cell rna sequencing. Nat Methods, 15, 539–542.

#' @references Zhang, X. F. et al. (2019) EnImpute: imputing dropout events in single cell RNA sequencing data via ensemble learning.

#'

"baron"
